
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stetic-services
  namespace: stetic-services
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daniland.t@gmail.com
    privateKeySecretRef: 
      name: letsencrypt-stetic-services
    solvers:
    - http01:
        ingress:
          class: nginx
