apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: demo-danweb-api
  namespace: demo-danweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-danweb-api
  template:
    metadata:
      labels:
        app: demo-danweb-api
    spec:
      containers:
        - name: demo-danweb-api
          image: williambr2022/solucao-api:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DbUser
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_user
            - name: Database
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: database
            - name: DbPort
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_port
            - name: DbServer
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: db_server
            - name: KeyMD5
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: key_md5
            - name: DocsPath
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: docs_path
            - name: ModelDocsPath
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: model_docs_path
            - name: Password
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
          volumeMounts:
          - name: contracts-storage
            mountPath: /var/opt/demo-danweb/contratos
          - name: models-storage
            mountPath: /var/opt/demo-danweb/modelos
      volumes:
      - name: contracts-storage
        persistentVolumeClaim:
          claimName: contracts-data
      - name: models-storage
        persistentVolumeClaim:
          claimName: models-data