insert into AttributeTypes ([key], [value]) VALUES ('Texto','string')
insert into AttributeTypes ([key], [value]) VALUES ('Data','datetime')
insert into AttributeTypes ([key], [value]) VALUES ('Hora','datetime')
insert into AttributeTypes ([key], [value]) VALUES ('Decimal','decimal')
insert into AttributeTypes ([key], [value]) VALUES ('Decimal Extenso','decimal_extenso')
insert into AttributeTypes ([key], [value]) VALUES ('Data Extenso','datetime_extenso')

insert into TechnicalAttributes ([key], [value]) VALUES ('Hora Início','StartTime')
insert into TechnicalAttributes ([key], [value]) VALUES ('Hora Término','EndTime')
insert into TechnicalAttributes ([key], [value]) VALUES ('Nome Locatário','Client.Name')
insert into TechnicalAttributes ([key], [value]) VALUES ('Nome Equipamento','Equipament.Name')
insert into TechnicalAttributes ([key], [value]) VALUES ('Data Locação','Date')
insert into TechnicalAttributes ([key], [value]) VALUES ('Valor','Value')